# Root path for the suites/playlists
# Relative paths are relative to the config file location
playlist-root = "~/skriini"

[plai]
socket = "/tmp/plai.sock"
run = false
path = "plai"
db = ":memory:"
log-level = "info"
fullscreen = false
image-duration = 1.0
blend-duration = 1.0

[plai.watermark]
path = ""
scaling = { w = 1.0, h = 1.0}

[playlist.adds]
globs = ["Mainokset/*.mp4"]

[playlist.pics]
globs = "Photo-screen/*.JPG"
filter = { algo = "newest", count = 20}

[playlist.wed]
from = ["prog_wed", "pics"]

[playlist.thu]
from = ["prog_thu", "pics"]

[playlist.fri]
from = ["prog_fri", "pics"]

[playlist.sat]
from = ["prog_sat", "pics"]

[playlist.prog_wed]
globs = "Ohjelma/KE/*.mp4"

[playlist.prog_thu]
globs = "Ohjelma/TO/*.mp4"

[playlist.prog_fri]
globs = "Ohjelma/PE/*.mp4"

[playlist.prog_sat]
globs = "Ohjelma/LA/*.mp4"

