# List of playlists, used to protect against typos
playlist_names = ["wed", "thu", "fri", "sat"]


# Keskiviikko
[[schedule]]
playlist = "wed"
at = 2026-06-01 00:00:00

# Torstai
[[schedule]]
playlist = "thu"
at = 2026-06-18 03:00:00

# Perjantai
[[schedule]]
playlist = "fri"
at = 2026-06-19 03:00:00

# Lauantai
[[schedule]]
playlist = "sat"
at = 2026-06-20 03:00:00
